import { CheckCircle2, ClipboardCheck, HeartPulse, Home, ShieldCheck, Users } from 'lucide-react'
import { Link } from 'react-router-dom'

const illustratedPrograms=[
  ['/programs/allergy.png','Allergy Care','Focused testing to help investigate allergy-related concerns.'],
  ['/programs/pregnancy.png','Pregnancy Wellness','Supportive health panels for key stages of pregnancy.'],
  ['/programs/cancer.png','Cancer Screening','Preventive screening guidance based on individual needs.'],
  ['/programs/wellness.png','Active Wellness','Everyday health checks for energy, balance and wellbeing.'],
  ['/programs/diabetes.png','Diabetes Care','Blood sugar monitoring and long-term metabolic support.'],
]

export function ProgramShowcase(){return <section className="section program-showcase"><div className="container"><div className="section-head"><div><span className="eyebrow">Special programs</span><h2>Focused care for different health journeys.</h2></div><p>Friendly, practical screening programs designed around common life stages and health concerns.</p></div><div className="illustrated-programs">{illustratedPrograms.map(([image,title,text])=><Link to="/contact" className="illustrated-program" key={title}><div className="program-illustration"><img src={image} alt=""/></div><div className="program-card-copy"><h3>{title}</h3><p>{text}</p><span>Explore program →</span></div></Link>)}</div></div></section>}

export function HomeExtra(){return <><section className="section soft-section"><div className="container"><div className="section-head"><div><span className="eyebrow">Health packages</span><h2>Preventive care for every stage of life.</h2></div><p>Thoughtfully grouped investigations make regular monitoring simpler for individuals and families.</p></div><div className="cards"><article className="card"><div className="card-icon"><HeartPulse/></div><h3>Essential Wellness</h3><p>Core blood, sugar, liver, kidney and lipid markers for a practical health overview.</p><Link className="text-link" to="/tests">View related tests</Link></article><article className="card"><div className="card-icon"><Users/></div><h3>Family Health</h3><p>Flexible screening support for adults, children and seniors in one convenient visit.</p><Link className="text-link" to="/contact">Plan a family visit</Link></article><article className="card"><div className="card-icon"><ShieldCheck/></div><h3>Ongoing Monitoring</h3><p>Regular panels for diabetes, thyroid, cholesterol and long-term health needs.</p><Link className="text-link" to="/contact">Ask for guidance</Link></article></div></div></section><section className="section"><div className="container split"><div><span className="eyebrow">A centre for everyone</span><h2>Practical diagnostics for everyday life.</h2><p className="lead">Whether this is your first health check or part of ongoing care, we make each visit easier to plan and understand.</p></div><div className="detail-list"><div><strong>Preventive checkups</strong><span>Stay informed about important health markers before symptoms appear.</span></div><div><strong>Chronic care monitoring</strong><span>Track changes over time and support informed follow-up decisions.</span></div><div><strong>Doctor-recommended tests</strong><span>Bring your prescription and we will guide you through preparation.</span></div><div><strong>Family health planning</strong><span>Coordinate routine testing for loved ones with less stress.</span></div></div></div></section></>}

export function AboutExtra(){return <><section className="section soft-section"><div className="container split"><div><span className="eyebrow">Our commitment</span><h2>Quality is a process, not a poster.</h2><p className="lead">We focus on careful handling, organised workflows and clear responsibility at every stage of testing.</p></div><div className="detail-list"><div><strong>Before analysis</strong><span>Patient identification, preparation guidance and careful sample collection.</span></div><div><strong>During analysis</strong><span>Structured laboratory processes and attention to equipment and controls.</span></div><div><strong>After analysis</strong><span>Report review, timely communication and collection guidance.</span></div></div></div></section><section className="section"><div className="container"><div className="section-head"><div><span className="eyebrow">Who we support</span><h2>Built for our community.</h2></div></div><div className="cards"><article className="card"><div className="card-icon"><Home/></div><h3>Individuals & families</h3><p>Accessible routine tests, preventive packages and ongoing health monitoring close to home.</p></article><article className="card"><div className="card-icon"><ClipboardCheck/></div><h3>Working professionals</h3><p>Convenient scheduling and clear turnaround guidance that respects busy routines.</p></article><article className="card"><div className="card-icon"><Users/></div><h3>Senior patients</h3><p>Patient, respectful support for recurring tests and age-related health screening.</p></article></div></div></section></>}

export function ServicesExtra(){return <><section className="section"><div className="container"><div className="section-head"><div><span className="eyebrow">More ways we help</span><h2>Testing that fits your care journey.</h2></div><p>Our services support prevention, diagnosis and regular monitoring.</p></div><div className="cards">{[['Preventive screening','Reveal changes early and support healthier decisions.'],['Condition monitoring','Understand how important markers change over time.'],['Pre-employment testing','Diagnostic support for workplace health requirements.'],['Family checkups','Coordinate essential testing for multiple family members.'],['Nutritional assessment','Vitamin and iron investigations for wellness planning.'],['Follow-up panels','Focused testing for review appointments and treatment decisions.']].map(([title,text])=><article className="card" key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></div></section><section className="section dark-section"><div className="container split"><div><span className="eyebrow">Service standards</span><h2>What you can expect from us.</h2></div><ul className="check-list light-list"><li><CheckCircle2/>Simple booking and preparation instructions</li><li><CheckCircle2/>Respectful collection by trained staff</li><li><CheckCircle2/>Careful sample handling and processing</li><li><CheckCircle2/>Transparent reporting timelines</li><li><CheckCircle2/>Support when you have questions</li></ul></div></section></>}

export function ContactExtra(){return <><section className="section soft-section"><div className="container"><div className="section-head"><div><span className="eyebrow">What happens next</span><h2>From request to report.</h2></div></div><div className="steps"><article className="step"><span className="step-number">1</span><h3>We confirm your visit</h3><p>We contact you to confirm the test, preferred time and preparation.</p></article><article className="step"><span className="step-number">2</span><h3>You visit the centre</h3><p>Bring your prescription and ID for a smooth registration and collection.</p></article><article className="step"><span className="step-number">3</span><h3>You receive your report</h3><p>We share the expected turnaround and explain report collection.</p></article></div></div></section><section className="section"><div className="container"><div className="section-head"><div><span className="eyebrow">Before you contact us</span><h2>Frequently asked questions.</h2></div></div><div className="cards"><article className="card"><h3>Can I book for a family member?</h3><p>Yes. Share their name, requested test and preferred date in the form.</p></article><article className="card"><h3>What if I do not know the test name?</h3><p>Select “Other / Not sure” and tell us your concern or prescription details.</p></article><article className="card"><h3>Do you accept walk-ins?</h3><p>Contact the centre to confirm current availability. Booking ahead is recommended.</p></article></div></div></section></>}
